# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 215c2ef9b6516200c56f48eb71ea929c4e860fa9fce36d3ddfdeba918d7b6d787fa08374ec12b81d7abfa008be0d1576934708b8df8e4a28663c1e326bf95ee4

test:
  secret_key_base: 9c051ed0797ae6186149c379f841571b3ee77da79babde35e86f6903f1b7d5efa392e72409e1882280b3a2f54680a9ef3a7f756fcceb3286399d94ee4c6b7b4b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
